#!/bin/bash

RESULT=/tmp/validation

date > "${RESULT}"
echo >> "${RESULT}"
lscpu >> "${RESULT}"
echo >> "${RESULT}"
uname -a >> "${RESULT}"
echo >> "${RESULT}"
cat /etc/locale.conf >> "${RESULT}"
free -m >> "${RESULT}"
echo >> "${RESULT}"
getenforce >> "${RESULT}"
echo >> "${RESULT}"
timedatectl >> "${RESULT}"
echo >> "${RESULT}"
lsblk >> "${RESULT}"
echo >> "${RESULT}"
cat /etc/fstab >> "${RESULT}"
echo >> "${RESULT}"
ip a >> "${RESULT}"
echo >> "${RESULT}"
lspci | grep net >> "${RESULT}"
echo >> "${RESULT}"
ls -al /sys/class/net/ >> "${RESULT}"
echo >> "${RESULT}"
hostname --fqdn >> "${RESULT}"
echo >> "${RESULT}"
python3 --version >> "${RESULT}"
echo >> "${RESULT}"
nmcli con show enp197s0f0 | grep ipv4.method >> "${RESULT}"
nmcli con show enp197s0f0 | grep ipv6.method >> "${RESULT}"
nmcli con show enp197s0f1 | grep ipv6.method >> "${RESULT}"
nmcli con show enp197s0f1 | grep ipv4.method >> "${RESULT}"
echo >> "${RESULT}"
systemctl status fastdpi >> "${RESULT}"
echo >> "${RESULT}"
cat /sys/devices/system/cpu/isolated >> "${RESULT}"
echo >> "${RESULT}"
cat /etc/dpi/fastdpi.lic >> "${RESULT}"
echo >> "${RESULT}"
cat /sys/devices/system/cpu/isolated >> "${RESULT}"
